creation_rules:
  # Production secrets: encrypted with primary + DR region KMS key pair
  # CI/CD pipeline must assume the ci-sops-prod-decrypt role to decrypt
  - path_regex: \.prod\.yaml$
    kms: >-
      arn:aws:kms:us-east-1:123456789012:key/11111111-2222-3333-4444-555555555555+arn:aws:iam::123456789012:role/ci-sops-prod-decrypt,
      arn:aws:kms:eu-west-1:123456789012:key/66666666-7777-8888-9999-000000000000

  # Staging secrets: encrypted with staging keys, accessible by broader CI role
  - path_regex: \.staging\.yaml$
    kms: >-
      arn:aws:kms:us-east-1:123456789012:key/22222222-3333-4444-5555-666666666666

  # Development secrets: encrypted with lower-tier keys, no IAM role constraint
  - path_regex: \.dev\.yaml$
    kms: >-
      arn:aws:kms:us-west-2:123456789012:key/33333333-4444-5555-6666-777777777777

  # Catch-all: any unmatched file gets most restrictive key
  - kms: >-
      arn:aws:kms:us-east-1:123456789012:key/11111111-2222-3333-4444-555555555555
