apiVersion: apps/v1
kind: Deployment
metadata:
  name: steel-browser
  namespace: ai
  labels:
    app: steel-browser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: steel-browser
  template:
    metadata:
      labels:
        app: steel-browser
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "scraper-role"
        vault.hashicorp.com/agent-inject-secret-proxy: "secret/data/ai/scraping-proxy"
        vault.hashicorp.com/agent-inject-template-proxy: |
          {{- with secret "secret/data/ai/scraping-proxy" -}}
          export PROXY_URL="http://{{ .Data.data.username }}:{{ .Data.data.password }}@{{ .Data.data.endpoint }}"
          {{- end -}}
    spec:
      serviceAccountName: steel-sa
      nodeSelector:
        pool: worker-high
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: steel-browser
        image: ghcr.io/steel-dev/steel-browser:latest
        ports:
        - name: http
          containerPort: 3000
        - name: cdp
          containerPort: 9223
        env:
        - name: STEEL_SESSION_STORE
          value: "redis" # Integration with platform Redis
        - name: REDIS_URL
          value: "redis://redis-master.infra.svc.cluster.local:6379"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: steel-browser
  namespace: ai
spec:
  ports:
  - port: 3000
    targetPort: http
    name: http
  - port: 9223
    targetPort: cdp
    name: cdp
  selector:
    app: steel-browser
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: steel-sa
  namespace: ai
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: steel-restrict-egress
  namespace: ai
spec:
  endpointSelector:
    matchLabels:
      app: steel-browser
  egress:
  - toEndpoints:
    - matchLabels:
        app: egress-gateway # Only allow talk to egress proxy
    toPorts:
    - ports:
      - port: "3128"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        app: redis # Allow talk to internal redis for sessions
    toPorts:
    - ports:
      - port: "6379"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system # Allow DNS
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      rules:
        dns:
        - matchPattern: "*"
